- hosts: terraform-ansible
  tasks:
    - name: Instalando o python3 e VirtualEnv
      apt:
        pkg: 
        - python3
        - virtualenv
        update-cache: yes # atualiza os repositorios
      become: yes # instala os pacotes como root
    - name: Instalando dependencias com pip (Django e Django Rest)
      pip:
        virtualenv: ~/tcc/venv
        name:
          - django
          - djangorestframework
    - name: Verificando se o projeto ja existe
      stat:
        path: ~/tcc/setup/settings.py
      register: projeto
    - name: Iniciando projeto
      shell: '. ~/tcc/venv/bin/activate; django-admin startproject setup /home/ubuntu/tcc/'
      when: not projeto.stat.exists
    - name: Alterando o hosts do settings
      lineinfile:
        path: ~/tcc/setup/settings.py
        regexp: 'ALLOWED_HOSTS'
        line: 'ALLOWED_HOSTS = ["*"]'
        backrefs: yes # se nao achar a regex, ele não altera
    - name: Ativando servico
      shell: '. ~/tcc/venv/bin/activate; nohup python ~/tcc/manage.py runserver 0.0.0.0:8000 &'